[package]
name = "xenoz-force-create"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.26"
solana-sdk = "1.18.26"
solana-client = "1.18.26"
mpl-token-metadata = "5.1.0"
tokio = { version = "1.38", features = ["full"] }

